# FROM ruby:2.5.1-alpine
# ENV BUNDLER_VERSION=2.0.2

# RUN apk add --update --no-cache \
#       binutils-gold \
#       build-base \
#       curl \
#       file \
#       g++ \
#       gcc \
#       git \
#       less \
#       libstdc++ \
#       libffi-dev \
#       libc-dev \
#       linux-headers \
#       libxml2-dev \
#       libxslt-dev \
#       libgcrypt-dev \
#       make \
#       netcat-openbsd \
#       nodejs \
#       openssl \
#       pkgconfig \
#       postgresql-dev \
#       python \
#       tzdata \
#       yarn

# RUN gem install bundler -v 2.0.2


# RUN mkdir /myapp
# WORKDIR /myapp
# COPY ./compose/ruby/config/Gemfile* /myapp/
# RUN bundle config build.nokogiri --use-system-libraries
# RUN bundle check || bundle install
# COPY . /myapp

#Dockerfile
FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev sqlite3 nodejs
RUN mkdir /myapp
WORKDIR /myapp
COPY ./compose/ruby/config/Gemfile /myapp/Gemfile
COPY ./compose/ruby/config/Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp