FROM ruby:2.5.1-alpine

# ENV
ENV BUNDLER_VERSION=2.0.2

# Add dependencies
RUN apt-get update -qq
RUN apt-get install -y build-essential libpq-dev sqlite3 nodejs yarn

# RUN apk add --update --no-cache \
#       binutils-gold \
#       build-base \
#       curl \
#       file \
#       g++ \
#       gcc \
#       git \
#       less \
#       libstdc++ \
#       libffi-dev \
#       libc-dev \
#       linux-headers \
#       libxml2-dev \
#       libxslt-dev \
#       libgcrypt-dev \
#       make \
#       netcat-openbsd \
#       nodejs \
#       openssl \
#       pkgconfig \
#       postgresql-dev \
#       python \
#       tzdata \
#       yarn

RUN gem install bundler -v ${BUNDLER_VERSION}

# Generate work directory
RUN mkdir /app
WORKDIR /app

# Copy Config
COPY ./compose/ruby/config/Gemfile ./
COPY ./compose/ruby/config/Gemfile.lock ./

RUN bundle config build.nokogiri --use-system-libraries

# Generate project
RUN bundle check || bundle install

# COPY package.json yarn.lock ./

# RUN yarn install --check-files

# Add source to project
COPY . ./

ENTRYPOINT ["./compose/ruby/entrypoint.sh"]