FROM ruby:2.5
# FROM ruby:2.5.1-alpine

# DotEnv
ENV APP_HOME /myapp
# ENV BUNDLER_VERSION=2.0.2

# Add dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev sqlite3 nodejs yarn

# Generate work directory
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Copy Config
COPY ./compose/ruby/config/Gemfile* $APP_HOME/
COPY ./compose/ruby/config/database.yml $APP_HOME/config/

# Generate project (Install dependencies)
RUN bundle config build.nokogiri --use-system-libraries
RUN bundle check || bundle install

# COPY package.json yarn.lock ./
# RUN yarn install --check-files

# Add source to project
COPY . $APP_HOME

# Add a script to be executed every time the container starts.
COPY ./compose/ruby/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

# Check Server
# RUN rm -f /rails/tmp/pids/server.cpid
