version: '3.8'

#Docker Networks
networks:
  rails_network:
    driver: bridge

#Volumes
volumes:
  node_modules:
    driver: local
  gem_cache:
    driver: local
  db_data:
    driver: local

services:
  database:
    image: postgres
    container_name: database
    env_file: .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rails_network

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rails_network

  ruby:
    build:
      context: .
      dockerfile: ./compose/ruby/DockerFile
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: ruby
    depends_on:
      - database
      - redis
    volumes:
      - ./source:/myapp
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - "3000:3000"
    networks:
      - rails_network

  rails:
    build:
      context: .
      dockerfile: ./compose/ruby/DockerFile
    container_name: rails
    volumes:
      - ./source:/myapp
    working_dir: /myapp
    depends_on:
      - ruby
    networks:
      - rails_network
    entrypoint: ['rails']
