version: '3.8'

#Docker Networks
networks:
  rails_network:
    driver: bridge

#Volumes
volumes:
  node_modules:
    driver: local
  gem_cache:
    driver: local
  db_data:
    driver: local

services:
  db:
    image: postgres
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rails_network

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rails_network

  ruby:
    build:
      context: .
      dockerfile: ./compose/ruby/DockerFile
    container_name: ruby
    depends_on:
      - db
      - redis
    volumes:
      - ./source:/myapp
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    networks:
      - rails_network
