version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - rails_network


  web:
    build:
      context: .
      dockerfile: ./compose/ruby/DockerFile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./source:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rails_network

networks:
  rails_network:
    driver: bridge
