version: '3.8'

#Docker Networks
networks:
  rails:
    driver: bridge

#Volumes
volumes:
  node_modules:
    driver: local
  gem_cache:
    driver: local
  db_data:
    driver: local

# Workflow
services:
  app:
    build: 
      context: .
      dockerfile: ./compose/ruby/DockerFile
    ports:
      - 3000:3000
    container_name: ruby
    depends_on:
      - database
      - redis
    volumes:
      - ./source:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    networks:
    - rails
    
  database:
    image: postgres:12.1
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
    - rails

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rails
